name: Python File Checker
on:
  push:
    branches:
      - main

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Run Python files
        run: python -m compileall .

      - name: Check for errors
        run: |
          if [ -z "$(find . -name '*.pyc')" ]; then
            echo "All Python files are error-free."
          else
            echo "Error: Some Python files have errors."
            exit 1

